[project]
# PEP 621: Project Metadata (The standardized info - 2020 approved)
# By using a standardized format, developers can switch between different build tools (like switching from setuptools to hatch) without rewriting their project metadata

name = "myapp"
version = "0.1.0"
description = "FastAPI production app"
authors = [
    { name = "Your Name" }
]
dependencies = [
    "fastapi",
    "uvicorn[standard]"
]

[build-system]     
# PEP 518: Build System Requirements (2016 approved)
# Tells pip: "Go get these tools first so you can build me!"

requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
dev = ["pytest", "black", "ruff"]       // pip install .[dev]